freebsd_instance:
  image_family: freebsd-13-0

task:
  env:
    CIRRUS_CLONE_DEPTH: 1
    IGNORE_OSVERSION: yes

  install_script:
    - date
    - uname -a
    - sudo pkg install -y git
    - curl -L -S https://github.com/Oldes/Rebol3/releases/download/3.14.0/rebol3-bulk-freebsd-x64.gz --output rebol3-bulk-freebsd-x64.gz
    - gunzip ./rebol3-bulk-freebsd-x64.gz
    - mv ./rebol3-bulk-freebsd-x64 ./rebol
    - chmod u+x ./rebol
    - ./rebol --version

  matrix:
    - name: Siskin FreeBSD x64
      script:
        - ./rebol siskin.r3 rebol/siskin siskin-freebsd-x86_64
        - mv ./tree/rebol/Siskin/build/siskin-freebsd-x86_64 ./
        - ./siskin-freebsd-x86_64 --version
        - gzip -9 ./siskin-freebsd-x86_64

  binaries_artifacts:
   path: "*.gz"
