name: 'Build Boron'
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_qoi:
    name: Boron
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
#         - windows-latest # needs installed zlib library on Windows 
          - macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rebol
      uses: oldes/install-rebol@v3.7.1

    - name: Build Boron
      run: ./rebol3 siskin.r3 boron 1

    - name: Test Boron
      run: ./tree/boron/build/boron ./tree/boron/code/test/func.b


    ###############################################################################
    # Collecting build artifacts...
    - uses: actions/upload-artifact@v2
      with:
        name: boron-${{matrix.os}}-CI-${{github.run_id}}
        path: ./tree/boron/build/*
