name: 'Build Brotli'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: true
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rebol
        uses: oldes/install-rebol@v3.11.0

      - name: Build 64bit Brotli using msvc
        run: |
          ./rebol3.exe siskin.r3 utility/brotli --msvc 1
          MOVE ./tree/utility/msvc/Release-x64/brotli.exe ./

      - name: Simple test
        run: ./brotli.exe -h

      - uses: actions/upload-artifact@v3
        with:
          name: brotli
          path: ./brotli.exe

  linux:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
        #os: [ubuntu-20.04, ubuntu-18.04]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rebol
        uses: oldes/install-rebol@v3.11.0

      - name: Build 64bit Brotli using gcc
        run: ./rebol3 siskin.r3 utility/brotli 1

      - name: Move results into the root for uploading
        run:  mv ./tree/utility/build/brotli ./brotli

      - name: Simple test
        run: chmod +x ./brotli & ./brotli -h

      - name: Compress results before uploading
        run: gzip -9 ./brotli

      - uses: actions/upload-artifact@v3
        with:
          name: brotli
          path: ./brotli.gz

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rebol
        uses: oldes/install-rebol@v3.11.0

      - name: Build 64bit Brotli
        run: ./rebol3 siskin.r3 utility/brotli 1

      - name: Move results into the root for uploading
        run: mv ./tree/utility/build/brotli ./brotli-osx

      - name: Simple test
        run: chmod +x ./brotli-osx & ./brotli-osx -h

      - name: Compress results before uploading
        run: gzip -9 ./brotli-osx

      - uses: actions/upload-artifact@v3
        with:
          name: brotli
          path: ./brotli-osx.gz
