name: BSD cross-compilation test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os:
#          - name: freebsd
#            architecture: x86-64
#            version: '13.1'
#            host: macos-12
#
#          - name: openbsd
#            architecture: x86-64
#            version: '7.2'
#            host: macos-12
#
#          - name: openbsd
#            architecture: arm64
#            version: '7.2'
#            host: ubuntu-latest
#
          - name: netbsd
            architecture: x86-64
            version: '9.2'
            host: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.10.0
        env:
          MY_ENV1: MY_ENV1
          MY_ENV2: MY_ENV2
        with:
          environment_variables: MY_ENV1 MY_ENV2
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            uname -a
            echo $SHELL
            wget https://github.com/Siskin-framework/Rebol/archive/refs/tags/3.7.2-bootstrap-alpine.tar.gz
            gunzip ./3.7.2-bootstrap-alpine.tar.gz
            pwd
            ls -lah
            cd ./3.7.2-bootstrap-alpine/make/
            make -f rebol-linux-bootstrap-64bit.mk
#            whoami
#            env | sort
      - name: Output
        run: ls -la ./tree/rebol/Rebol/build/  
