name: 'Build LZFSE'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: true
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rebol
        uses: oldes/install-rebol@v3.5.5

      - name: Build 64bit LZFSE using msvc
        run: |
          ./rebol3.exe siskin.r3 utility/lzfse [msvc 1]
          MOVE ./tree/utility/msvc/Release-x64/lzfse.exe ./

      - uses: actions/upload-artifact@v2
        with:
          name: lzfse
          path: ./lzfse.exe

  linux:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-18.04]
        #os: [ubuntu-20.04, ubuntu-18.04]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rebol
        uses: oldes/install-rebol@v3.5.5

      - name: Build 64bit LZFSE using gcc
        run: ./rebol3 siskin.r3 utility/lzfse 1

      - name: Move results into the root for uploading
        run:  mv ./tree/utility/build/lzfse ./lzfse

      - name: Compress results before uploading
        run: gzip -9 ./lzfse

      - uses: actions/upload-artifact@v2
        with:
          name: lzfse
          path: ./lzfse.gz

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rebol
        uses: oldes/install-rebol@v3.5.5

      - name: Build 64bit LZFSE
        run: ./rebol3 siskin.r3 utility/lzfse 1

      - name: Move results into the root for uploading
        run: mv ./tree/utility/build/lzfse ./lzfse-osx

      - name: Compress results before uploading
        run: gzip -9 ./lzfse-osx

      - uses: actions/upload-artifact@v2
        with:
          name: lzfse
          path: ./lzfse-osx.gz
