name: 'Build LZFSE'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: true
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Siskin Builder
        shell: cmd
        run: |
          C:\msys64\usr\bin\wget.exe -q https://github.com/Siskin-framework/Builder/releases/download/0.3.3/Siskin-x64.exe
          MOVE ./Siskin-x64.exe ./siskin.exe
          SET PATH=%PATH%;%CD%

      - name: Build 64bit LZFSE using msvc
        run: |
          ./siskin.exe utility/lzfse [msvc 1]
          MOVE ./tree/utility/lzfse/msvc/Release-x64/lzfse.exe ./

      - uses: actions/upload-artifact@v2
        with:
          name: lzfse
          path: ./lzfse.exe

  linux:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-18.04]
        #os: [ubuntu-20.04, ubuntu-18.04]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Download Siskin Builder
        run: |
          wget -q https://github.com/Siskin-framework/Builder/releases/download/0.3.3/Siskin-x64-libc.gz
          gunzip ./Siskin-x64-libc.gz
          mv ./Siskin-x64-libc ./siskin
          chmod +x ./siskin

      - name: Build 64bit LZFSE using gcc
        run: ./siskin utility/lzfse 1

      - name: Move results into the root for uploading
        run:  mv ./tree/utility/lzfse/build/lzfse ./lzfse

      - name: Compress results before uploading
        run: gzip -9 ./lzfse

      - uses: actions/upload-artifact@v2
        with:
          name: lzfse
          path: ./lzfse.gz

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Siskin Builder
        run: |
          wget -q https://github.com/Siskin-framework/Builder/releases/download/0.3.3/Siskin-x64-osx.gz
          gunzip ./Siskin-x64-osx.gz
          mv ./Siskin-x64-osx ./siskin
          chmod +x ./siskin
          ls -la

      - name: Build 64bit LZFSE
        run: ./siskin utility/lzfse 1

      - name: Move results into the root for uploading
        run: mv ./tree/utility/lzfse/build/lzfse ./lzfse-osx

      - name: Compress results before uploading
        run: gzip -9 ./lzfse-osx

      - uses: actions/upload-artifact@v2
        with:
          name: lzfse
          path: ./lzfse-osx.gz
