name: Test OpenBSD Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in OpenBSD
    env:
#      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v4
    - name: Test in OpenBSD
      id: test
      uses: vmactions/openbsd-vm@v1
      with:
        envs: 'MYTOKEN2'
        usesh: true
        prepare: |
          pkg_add curl git

        run: |
          git clone https://github.com/Siskin-framework/Rebol.git --depth 1 --quiet
          git checkout bootstrap
          cd ./Rebol/make/
          make -f rebol-linux-bootstrap-64bit.mk
          cd ../..
          mv ./Rebol/make/rebol-linux-bootstrap-64bit ./rebol
          ./rebol -v
          echo "Rebol [] unprotect 'system/platform system/platform: 'openbsd" > ~/user.reb
          ls -lah
          ./rebol siskin.r3 rebol %rebol3-bulk-openbsd-x64
#          curl -L -S https://github.com/Siskin-framework/Builder/releases/download/0.7.2/Siskin-x64-openbsd.gz --output siskin.gz
#          gunzip ./siskin.gz
#          chmod u+x ./siskin
#          ln -s /usr/lib/libc.so.97.1 /usr/lib/libc.so.96.1
#          ./siskin rebol %rebol3-bulk-openbsd-x64
#          mv ./tree/rebol/Rebol/build/rebol3-bulk-openbsd-x64 ./rebol3-bulk-openbsd-x64
#          ./rebol3-bulk-openbsd-x64 siskin.r3 rebol/siskin 2
#          mv ./tree/rebol/Siskin/build/siskin-openbsd-x86_64 ./siskin-openbsd-x86_64
#
    - name: Prepare build results
      run:  |
        gzip -9 ./rebol3-bulk-openbsd-x64
#        gzip -9 ./siskin-openbsd-x86_64
#
    - uses: actions/upload-artifact@v3
      with:
        name: Rebol-OpenBSD-${{github.run_id}}
        path: ./rebol3*.gz
#    - uses: actions/upload-artifact@v3
#      with:
#        name: Siskin-OpenBSD-${{github.run_id}}
#        path: ./siskin*.gz