name: 'Build Siskin'
on:
  # Triggers the workflow when these files are modified
  push:
    paths:
      - test/**
      - tree/rebol/Siskin/**
      - tree/rebol/siskin.nest
      - .github/workflows/siskin.yml

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: true
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rebol
        uses: oldes/install-rebol@v3.10.0

      # 32bit gcc version would fail for now (requires 32bit mingw)
      #    - name: Build 32bit Siskin using gcc
      #      run: |
      #        ./rebol3 siskin.r3 rebol/siskin %Siskin-x86
      #        MOVE ./tree/rebol/Siskin/build/Siskin-x86.exe ./Siskin-x86-gcc.exe
      # 
      #    - name: Build 64bit Siskin using gcc
      #      run: |
      #        ./rebol3 siskin.r3 rebol/siskin %Siskin-x64
      #        MOVE ./tree/rebol/Siskin/build/Siskin-x64.exe ./Siskin-x64-gcc.exe

      - name: Build 32bit Siskin using msvc
        run: |
          ./rebol3 siskin.r3 rebol/siskin --msvc %Siskin-x86
          MOVE ./tree/rebol/Rebol/msvc/Release-Win32/Siskin-x86.exe ./

      - name: Build 64bit Siskin using msvc
        run: |
          ./rebol3 siskin.r3 rebol/siskin --msvc %Siskin-x64
          MOVE ./tree/rebol/Rebol/msvc/Release-x64/Siskin-x64.exe ./

      #- name: Test 32bit Siskin project (gcc)
      #  run: ./Siskin-x86-gcc.exe
      #- name: Test 64bit Siskin project (gcc)
      #  run: ./Siskin-x64-gcc.exe
      - name: Test 32bit Siskin project (msvc)
        run: ./Siskin-x86.exe
      - name: Test 64bit Siskin project (msvc)
        run: ./Siskin-x64.exe

      - name: List all possible test targets
        run: ./Siskin-x64.exe test --list
      - name: Test build 1
        run: ./Siskin-x64.exe test test-1
      - name: Test build 2
        run: ./Siskin-x64.exe test test-2
      - name: Test build 3
        run: ./Siskin-x64.exe test test-3
      - name: Test build 4
        run: ./Siskin-x64.exe test test-4
      - name: Test build 5
        run: ./Siskin-x64.exe test test-5
      - name: Test build 6
        run: ./Siskin-x64.exe test test-6
      - name: Test build 7
        run: ./Siskin-x64.exe test test-7
      - name: Test build 8
        run: ./Siskin-x64.exe test "test-8 spaced"
      - name: Test build multiple at once
        run: ./Siskin-x64.exe test 1 2 "test-8 spaced"

      - name: Test Rebol Preprocessor
        run: |
          ./Siskin-x64.exe test test.r3
          ./rebol3 ./build/test.r3

      - name: Test build 8 (MSVC)
        run: ./Siskin-x64.exe test --msvc 8      

      - uses: actions/upload-artifact@v2
        with:
          name: Siskin-windows
          path: |
            ./Siskin-x86.exe
            ./Siskin-x64.exe
          #  ./Siskin-x86-gcc.exe
          #  ./Siskin-x64-gcc.exe

  linux:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-20.04, ubuntu-18.04]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rebol
        uses: oldes/install-rebol@v3.10.0

      #- name: Build 32bit Siskin using gcc
      #  run: ./rebol3 siskin.r3 rebol/siskin %Siskin-x86-libc

      - name: Build 64bit Siskin using gcc
        run: ./rebol3 siskin.r3 rebol/siskin %Siskin-x64-libc

      - name: Move results into the root for uploading
        run: |
          mv ./tree/rebol/Siskin/build/Siskin-x64-libc ./
        #  mv ./tree/rebol/Siskin/build/Siskin-x86-libc ./

      - name: List all possible test targets
        run: ./Siskin-x64-libc test --list
      - name: Test build 1
        run: ./Siskin-x64-libc test test-1
      - name: Test build 2
        run: ./Siskin-x64-libc test test-2
      - name: Test build 3
        run: ./Siskin-x64-libc test test-3
      - name: Test build 4
        run: ./Siskin-x64-libc test test-4
      - name: Test build 5
        run: ./Siskin-x64-libc test test-5
      - name: Test build 6
        run: ./Siskin-x64-libc test test-6
      - name: Test build 7
        run: ./Siskin-x64-libc test test-7
      - name: Test build 8
        run: ./Siskin-x64-libc test "test-8 spaced"
      - name: Test build multiple at once
        run: ./Siskin-x64-libc test 1 2 "test-8 spaced"

      - name: Test Rebol Preprocessor
        run: |
          ./Siskin-x64-libc test test.r3
          ./rebol3 ./build/test.r3 

      - name: Compress results before uploading
        run: |
          gzip -9 ./Siskin-x64-libc
        #  gzip -9 ./Siskin-x86-libc

      - uses: actions/upload-artifact@v2
        with:
          name: Siskin-linux
          path: ./Siskin-x*

  macos:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rebol
        uses: oldes/install-rebol@v3.10.0

      - name: Install the Apple certificate
      # https://docs.github.com/en/actions/guides/installing-an-apple-certificate-on-macos-runners-for-xcode-development
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # list available codesigning identities
          security find-identity -v -p codesigning

      #It looks it's not possible to build 32bit macOS version anymore using GitHub actions!
      #
      #- name: Build 32bit Siskin
      #  run: |
      #    ./rebol3 siskin.r3 rebol/siskin %Siskin-x86-osx
      #    mv ./tree/rebol/Siskin/build/Siskin-x86-osx ./

      - name: Build 64bit Siskin
        run: ./rebol3 siskin.r3 rebol/siskin %Siskin-x64-osx

      - name: Build ARM64 Siskin
        run: ./rebol3 siskin.r3 rebol/siskin %Siskin-arm-osx

      - name: Move results into the root for uploading
        run: |
          mv ./tree/rebol/Siskin/build/Siskin-x64-osx ./
          mv ./tree/rebol/Siskin/build/Siskin-arm-osx ./

      - name: Codesign executables
        env: 
          MACOS_IDENTITY_ID: ${{ secrets.MACOS_IDENTITY_ID }}
        run: |
          /usr/bin/codesign --force -s $MACOS_IDENTITY_ID ./Siskin-x64-osx -v
          /usr/bin/codesign --force -s $MACOS_IDENTITY_ID ./Siskin-arm-osx -v
       

      - name: List all possible test targets
        run: ./Siskin-x64-osx test --list
      - name: Test build 1
        run: ./Siskin-x64-osx test test-1
      - name: Test build 2
        run: ./Siskin-x64-osx test test-2
      - name: Test build 3
        run: ./Siskin-x64-osx test test-3
      - name: Test build 4
        run: ./Siskin-x64-osx test test-4
      - name: Test build 5
        run: ./Siskin-x64-osx test test-5
      - name: Test build 6
        run: ./Siskin-x64-osx test test-6
      - name: Test build 7
        run: ./Siskin-x64-osx test test-7
      - name: Test build 8
        run: ./Siskin-x64-osx test "test-8 spaced"
      - name: Test build multiple at once
        run: ./Siskin-x64-osx test 1 2 "test-8 spaced"

      - name: Test Rebol Preprocessor
        run: |
          ./Siskin-x64-osx test test.r3
          ./rebol3 ./build/test.r3

      - name: Compress results before uploading
        run: gzip -9 ./Siskin-x64-osx

      - uses: actions/upload-artifact@v2
        with:
          name: Siskin-osx
          path: ./Siskin-x*
