name: 'Build Siskin'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: true
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rebol
        uses: oldes/install-rebol@v3.5.5

      # 32bit gcc version would fail for now (requires 32bit mingw)
      #    - name: Build 32bit Siskin using gcc
      #      run: |
      #        ./rebol3 siskin.r3 rebol/siskin %Siskin-x86
      #        MOVE ./tree/rebol/Siskin/build/Siskin-x86.exe ./Siskin-x86-gcc.exe
      # 
      #    - name: Build 64bit Siskin using gcc
      #      run: |
      #        ./rebol3 siskin.r3 rebol/siskin %Siskin-x64
      #        MOVE ./tree/rebol/Siskin/build/Siskin-x64.exe ./Siskin-x64-gcc.exe

      - name: Build 32bit Siskin using msvc
        run: |
          ./rebol3 siskin.r3 rebol/siskin [msvc %Siskin-x86]
          MOVE ./tree/rebol/Rebol/msvc/Release-Win32/Siskin-x86.exe ./
      - name: Build 64bit Siskin using msvc
        run: |
          ./rebol3 siskin.r3 rebol/siskin [msvc %Siskin-x64]
          MOVE ./tree/rebol/Rebol/msvc/Release-x64/Siskin-x64.exe ./

      #- name: Test 32bit Siskin project (gcc)
      #  run: ./Siskin-x86-gcc.exe
      #- name: Test 64bit Siskin project (gcc)
      #  run: ./Siskin-x64-gcc.exe
      - name: Test 32bit Siskin project (msvc)
        run: ./Siskin-x86.exe
      - name: Test 64bit Siskin project (msvc)
        run: ./Siskin-x64.exe

      - uses: actions/upload-artifact@v2
        with:
          name: Siskin-windows
          path: |
            ./Siskin-x86.exe
            ./Siskin-x64.exe
          #  ./Siskin-x86-gcc.exe
          #  ./Siskin-x64-gcc.exe

  linux:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-18.04]
        #os: [ubuntu-20.04, ubuntu-18.04]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rebol
        uses: oldes/install-rebol@v3.5.5

      #- name: Build 32bit Siskin using gcc
      #  run: ./rebol3 siskin.r3 rebol/siskin %Siskin-x86-libc

      - name: Build 64bit Siskin using gcc
        run: ./rebol3 siskin.r3 rebol/siskin %Siskin-x64-libc

      - name: Move results into the root for uploading
        run: |
          mv ./tree/rebol/Siskin/build/Siskin-x64-libc ./
        #  mv ./tree/rebol/Siskin/build/Siskin-x86-libc ./

      - name: Compress results before uploading
        run: |
          gzip -9 ./Siskin-x64-libc
        #  gzip -9 ./Siskin-x86-libc

      - uses: actions/upload-artifact@v2
        with:
          name: Siskin-linux
          path: ./Siskin-x*

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rebol
        uses: oldes/install-rebol@v3.5.5

      #It looks it's not possible to build 32bit macOS version anymore using GitHub actions!
      #
      #- name: Build 32bit Siskin
      #  run: |
      #    ./rebol3 siskin.r3 rebol/siskin %Siskin-x86-osx
      #    mv ./tree/rebol/Siskin/build/Siskin-x86-osx ./

      - name: Build 64bit Siskin
        run: ./rebol3 siskin.r3 rebol/siskin %Siskin-x64-osx

      - name: Move results into the root for uploading
        run: mv ./tree/rebol/Siskin/build/Siskin-x64-osx ./

      - name: Compress results before uploading
        run: gzip -9 ./Siskin-x64-osx

      - uses: actions/upload-artifact@v2
        with:
          name: Siskin-osx
          path: ./Siskin-x*
