name: 'Build Siskin'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: true
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout Rebol repository
      uses: actions/checkout@v2
      with:
        repository: Siskin-framework/Rebol
        path: tree/rebol/Rebol
        #ref:  new-make

    - name: Download Rebol
      shell: cmd
      run: |
        C:\msys64\usr\bin\wget.exe -q https://github.com/Siskin-framework/Rebol/releases/download/3.5.2/rebol3-core-x86-vs.exe
        MOVE ./rebol3-core-x86-vs.exe ./rebol3.exe
        SET PATH=%PATH%;%CD%

    - name: Build 32bit Siskin using gcc
      run: ./rebol3 ./tree/rebol/Siskin/siskin.r3 rebol/siskin %Siskin-x86-gcc
    - name: Build 64bit Siskin using gcc
      run: ./rebol3 ./tree/rebol/Siskin/siskin.r3 rebol/siskin %Siskin-x64-gcc

    - name: Build 32bit Siskin using msvc
      run: ./rebol3 ./tree/rebol/Siskin/siskin.r3 rebol/siskin [msvc %Siskin-x86-gcc]
    - name: Build 64bit Siskin using msvc
      run: ./rebol3 ./tree/rebol/Siskin/siskin.r3 rebol/siskin [msvc %Siskin-x64-gcc]

    - name: Test 32bit Siskin project (gcc)
      run: ./tree/rebol/Siskin/build/Siskin-x86-gcc.exe
    - name: Test 64bit Siskin project (gcc)
      run: ./tree/rebol/Siskin/build/Siskin-x64-gcc.exe

    # at this moment, MSVC results are in MSVC folder
    - name: Test 32bit Siskin project (msvc)
      run: ./tree/rebol/Rebol/msvc/Release-Win32/Siskin-x86-vs.exe
    - name: Test 64bit Siskin project (msvc)
      run: ./tree/rebol/Rebol/msvc/Release-x64/Siskin-x64-vs.exe

    - uses: actions/upload-artifact@v2
      with:
        name: Siskin-x86-win
        path: |
          ./projects/rebol/Rebol/build/Siskin-x86-gcc.exe
          ./projects/rebol/Rebol/msvc/Release-Win32/Siskin-x86-vs.exe

    - uses: actions/upload-artifact@v2
      with:
        name: Siskin-x64-win
        path: |
          ./projects/rebol/Rebol/build/Siskin-x64-gcc.exe
          ./projects/rebol/Rebol/msvc/Release-x64/Siskin-x64-vs.exe
