name: 'Just a test of Github actions'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - .github/workflows/test.yml
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  OUT: ${{github.WORKSPACE}}/Release/
  REBOL_MODULES_DIR: ${{env.OUT}}

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Info
      shell: bash
      run: |
        echo "Temp: $RUNNER_TEMP Test: $REBOL_MODULES_DIR"

  linux:
    runs-on: ubuntu-20.04
    env:
      REBOL_MODULES_DIR: ~/rebol/modules/

    steps:
    - name: Info
      run: |
        echo "Temp: $RUNNER_TEMP Test: $REBOL_MODULES_DIR"

  macos:
    runs-on: macos-latest
    env:
      REBOL_MODULES_DIR: ~/rebol/modules/

    steps:
    - name: Info
      run: |
        echo "Temp: $RUNNER_TEMP Test: $REBOL_MODULES_DIR"
