name: 'Just a test of Github actions'
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Info
      run: |
        echo "RUNNER_TEMP: %RUNNER_TEMP% $RUNNER_TEMP"

  linux:
    runs-on: ubuntu-20.04

    steps:
    - name: Info
      run: |
        echo "RUNNER_TEMP: $RUNNER_TEMP"

  macos:
    runs-on: macos-latest

    steps:
    - name: Info
      run: |
        echo "RUNNER_TEMP: $RUNNER_TEMP"
