name: 'Just a test of Github actions'
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    env:
      REBOL_MODULES_DIR: ${{env.TEMP}}/modules/

    steps:
    - name: Info
      shell: bash
      run: |
        echo "Temp: $RUNNER_TEMP Test: $REBOL_MODULES_DIR"

  linux:
    runs-on: ubuntu-20.04
    env:
      REBOL_MODULES_DIR: ~/rebol/modules/

    steps:
    - name: Info
      run: |
        echo "Temp: $RUNNER_TEMP Test: $REBOL_MODULES_DIR"

  macos:
    runs-on: macos-latest
    env:
      REBOL_MODULES_DIR: ~/rebol/modules/

    steps:
    - name: Info
      run: |
        echo "Temp: $RUNNER_TEMP Test: $REBOL_MODULES_DIR"
