name: 'Build Triangle'
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_triangle:
    name: Triangle
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rebol
      uses: oldes/install-rebol@v3.6.0

    - name: Build 64bit Traingle utility
      run: ./rebol3 siskin.r3 utility/triangle triangle-x64

    - name: Test 64bit Triangle
      run: ./tree/utility/triangle/build/triangle-x64

    ###############################################################################
    # Collecting build artifacts...
    - uses: actions/upload-artifact@v2
      with:
        name: Triangle-${{matrix.os}}-CI-${{github.run_id}}
        path: ./tree/utility/triangle/build/*
